"""added User Type model and schema tables

Revision ID: 004c35d357e9
Revises: 3daf0a5f3b75
Create Date: 2025-11-03 15:00:16.066874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004c35d357e9'
down_revision: Union[str, Sequence[str], None] = '3daf0a5f3b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('monthly_charge', sa.Numeric(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_types_id'), 'user_types', ['id'], unique=False)
    op.add_column('subscriptions', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_method', sa.String(), nullable=True))
    op.alter_column('subscriptions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.drop_column('subscriptions', 'expires_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'plan_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('subscriptions', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('subscriptions', 'payment_method')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'plan')
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types')
    op.drop_table('user_types')
    # ### end Alembic commands ###
