"""added mp table and mp relationship in the message table

Revision ID: 08614b68d7ca
Revises: 42dab8a61702
Create Date: 2025-10-13 13:01:30.679203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08614b68d7ca'
down_revision: Union[str, Sequence[str], None] = '42dab8a61702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('mp_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'mps', ['mp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'mp_id')
    # ### end Alembic commands ###
