"""add response and response_id to message for mp reply for ussd

Revision ID: 35b52d91e498
Revises: 59e00dda9bf8
Create Date: 2025-10-12 09:47:49.939448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b52d91e498'
down_revision: Union[str, Sequence[str], None] = '59e00dda9bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('responded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'responded_at')
    op.drop_column('messages', 'response')
    # ### end Alembic commands ###
