"""Add media_url to comments

Revision ID: 53ddf50d3528
Revises: 582bad806cc0
Create Date: 2025-10-08 15:33:24.049472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ddf50d3528'
down_revision: Union[str, Sequence[str], None] = '582bad806cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('media_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'media_url')
    # ### end Alembic commands ###
