"""add updated_at to ussd_sessions

Revision ID: 582bad806cc0
Revises: badc0798032e
Create Date: 2025-10-06 16:19:54.323398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582bad806cc0'
down_revision: Union[str, Sequence[str], None] = 'badc0798032e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ussd_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ussd_sessions', 'updated_at')
    # ### end Alembic commands ###
