"""added tables to group

Revision ID: 59428d784db4
Revises: ad5f7b830301
Create Date: 2025-10-27 10:56:05.606139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59428d784db4'
down_revision: Union[str, Sequence[str], None] = 'ad5f7b830301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'village_id')
    op.drop_column('users', 'sub_county_id')
    op.drop_column('users', 'parish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parish_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sub_county_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('village_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    # ### end Alembic commands ###
