"""Fix district_id nullable in mps table

Revision ID: 7001dfb297f1
Revises: 4c99ed4bc4ff
Create Date: 2025-10-13 16:34:48.381081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7001dfb297f1'
down_revision: Union[str, Sequence[str], None] = '4c99ed4bc4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mps', 'district_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mps', 'district_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
