"""dropping some column in user table

Revision ID: 76accbf543f1
Revises: c55579411eaa
Create Date: 2025-10-20 18:47:28.520947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76accbf543f1'
down_revision: Union[str, Sequence[str], None] = 'c55579411eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'village_id')
    op.drop_column('users', 'sub_county_id')
    op.drop_column('users', 'parish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parish_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sub_county_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('village_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
