"""add search_vector columns to searchable models

Revision ID: 78bb6d4c0bda
Revises: 8ebe31796aac
Create Date: 2025-11-02 09:43:34.614264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.ts_vector


# revision identifiers, used by Alembic.
revision: str = '78bb6d4c0bda'
down_revision: Union[str, Sequence[str], None] = '8ebe31796aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.drop_index(op.f('idx_articles_search_tsv'), table_name='articles', postgresql_using='gin')
    op.drop_index(op.f('idx_articles_tsv_gin'), table_name='articles', postgresql_using='gin')
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('groups', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.add_column('live_feeds', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('topics', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.add_column('users', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_vector')
    op.drop_column('topics', 'search_vector')
    op.drop_column('live_feeds', 'updated_at')
    op.drop_column('groups', 'search_vector')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.create_index(op.f('idx_articles_tsv_gin'), 'articles', [sa.literal_column("to_tsvector('english'::regconfig, tsv_document)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_articles_search_tsv'), 'articles', [sa.literal_column('((setweight(to_tsvector(\'english\'::regconfig, COALESCE(title, \'\'::character varying)::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(summary, \'\'::text)), \'B\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, COALESCE(content, \'\'::text)), \'C\'::"char"))')], unique=False, postgresql_using='gin')
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###
