"""added is_active to LiveFeeds model table

Revision ID: 83367848dfdc
Revises: 59428d784db4
Create Date: 2025-10-27 11:42:42.449561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83367848dfdc'
down_revision: Union[str, Sequence[str], None] = '59428d784db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_feeds', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_feeds', 'is_active')
    # ### end Alembic commands ###
