"""Add is_featured to articles

Revision ID: a1ab67274b10
Revises: e50c5c7c96ed
Create Date: 2025-10-31 07:32:09.772833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ab67274b10'
down_revision: Union[str, Sequence[str], None] = 'e50c5c7c96ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_featured')
    # ### end Alembic commands ###
