"""Added owner_id and owner relationship to Group

Revision ID: ad5f7b830301
Revises: f69407038b03
Create Date: 2025-10-27 09:51:26.334893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5f7b830301'
down_revision: Union[str, Sequence[str], None] = 'f69407038b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    # ### end Alembic commands ###
