"""add ussd_sessions

Revision ID: badc0798032e
Revises: 930953331187
Create Date: 2025-10-03 19:48:25.909132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badc0798032e'
down_revision: Union[str, Sequence[str], None] = '930953331187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ussd_sessions_phone'), table_name='ussd_sessions')
    op.drop_constraint(op.f('ussd_sessions_phone_number_session_id_key'), 'ussd_sessions', type_='unique')
    op.create_index(op.f('ix_ussd_sessions_id'), 'ussd_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ussd_sessions_id'), table_name='ussd_sessions')
    op.create_unique_constraint(op.f('ussd_sessions_phone_number_session_id_key'), 'ussd_sessions', ['phone_number', 'session_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ussd_sessions_phone'), 'ussd_sessions', ['phone_number'], unique=False)
    # ### end Alembic commands ###
