"""Add user_id to MP

Revision ID: c55579411eaa
Revises: 0cc8a1f61058
Create Date: 2025-10-15 10:49:15.960689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55579411eaa'
down_revision: Union[str, Sequence[str], None] = '0cc8a1f61058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mps', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('mps', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'mps', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mps', type_='unique')
    op.drop_column('mps', 'updated_at')
    op.drop_column('mps', 'created_at')
    # ### end Alembic commands ###
